submit50:
  files: &submit50_files
    - !exclude "*"
    - !include "*.py"
    - !require mario.py

check50:
  files: *submit50_files

lab50:
  files:
    - !exclude "*"
    - !include mario.py
    - !include pseudocode.txt
    
